insert into goal_types (goal_name,ntrans) values ('sniff vanilla','endorphin');
insert into goal_types (goal_name,ntrans) values ('sniff lavender','endorphin');
insert into goal_types (goal_name,ntrans) values ('ginseng','endorphin');
insert into goal_types (goal_name,ntrans) values ('group exercise','endorphin');
insert into goal_types (goal_name,ntrans) values ('laughter','endorphin');
insert into goal_types (goal_name,ntrans) values ('sex','endorphin');
insert into goal_types (goal_name,ntrans) values ('chocolate','endorphin');
insert into goal_types (goal_name,ntrans) values ('listen to music','endorphin');
insert into goal_types (goal_name,ntrans) values ('eat something spicy','endorphin');
insert into goal_types (goal_name,ntrans) values ('volunteer','endorphin');
insert into goal_types (goal_name,ntrans) values ('go for a run','endorphin');
insert into goal_types (goal_name,ntrans) values ('listen with your eyes','oxytocin');
insert into goal_types (goal_name,ntrans) values ('give a gift','oxytocin');
insert into goal_types (goal_name,ntrans) values ('share a meal','oxytocin');
insert into goal_types (goal_name,ntrans) values ('meditate','oxytocin');
insert into goal_types (goal_name,ntrans) values ('soak in a hot tub','oxytocin');
insert into goal_types (goal_name,ntrans) values ('use social media','oxytocin');
insert into goal_types (goal_name,ntrans) values ('ride a roller coaster','oxytocin');
insert into goal_types (goal_name,ntrans) values ('pet a dog','oxytocin');
insert into goal_types (goal_name,ntrans) values ('tell someone you love them','oxytocin');
