insert into goal_types (goal_name,ntrans,type) values ('sniff vanilla','endorphin','diet');
insert into goal_types (goal_name,ntrans,type) values ('sniff lavender','endorphin','diet');
insert into goal_types (goal_name,ntrans,type) values ('ginseng','endorphin','diet');
insert into goal_types (goal_name,ntrans,type) values ('group exercise','endorphin','social');
insert into goal_types (goal_name,ntrans,type) values ('laughter','endorphin','social');
insert into goal_types (goal_name,ntrans,type) values ('sex','endorphin','social');
insert into goal_types (goal_name,ntrans,type) values ('chocolate','endorphin','diet');
insert into goal_types (goal_name,ntrans,type) values ('listen to music','endorphin','activity');
insert into goal_types (goal_name,ntrans,type) values ('eat something spicy','endorphin','diet');
insert into goal_types (goal_name,ntrans,type) values ('volunteer','endorphin','social');
insert into goal_types (goal_name,ntrans,type) values ('go for a run','endorphin','activity');
insert into goal_types (goal_name,ntrans,type) values ('listen with your eyes','oxytocin','social');
insert into goal_types (goal_name,ntrans,type) values ('give a gift','oxytocin','social');
insert into goal_types (goal_name,ntrans,type) values ('share a meal','oxytocin','social');
insert into goal_types (goal_name,ntrans,type) values ('meditate','oxytocin','diet');
insert into goal_types (goal_name,ntrans,type) values ('soak in a hot tub','oxytocin','diet');
insert into goal_types (goal_name,ntrans,type) values ('use social media','oxytocin','social');
insert into goal_types (goal_name,ntrans,type) values ('ride a roller coaster','oxytocin','activity');
insert into goal_types (goal_name,ntrans,type) values ('pet a dog','oxytocin','social');
insert into goal_types (goal_name,ntrans,type) values ('tell someone you love them','oxytocin','social');
insert into goal_types (goal_name,ntrans,type) values ('learn a language','serotonin','plan');
insert into goal_types (goal_name,ntrans,type) values ('organise your finances','serotonin','plan');
insert into goal_types (goal_name,ntrans,type) values ('procrastinate less','serotonin','plan');
insert into goal_types (goal_name,ntrans,type) values ('read a self help book','serotonin','plan');
insert into goal_types (goal_name,ntrans,type) values ('create a 5 year plan','serotonin','plan');
insert into goal_types (goal_name,ntrans,type) values ('read someones inspiring life story','serotonin','plan');
